Models/DB/Carro.cs
namespace Exercicio1.Models.DB
{
    public class Carro
    {
        public int Id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int AnoLancamento { get; set; }
        public int AnoMontagem { get; set; }
        public string Chassis { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Exercicio1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CarroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Exercicio1.Data;
using Exercicio1.Models.DB;

namespace Exercicio1.Controllers
{
    public class CarroController : Controller
    {
        private readonly appContext _context;

        public CarroController(appContext context)
        {
            _context = context;
        }

        // GET: Carro
        public async Task<IActionResult> Index()
        {
            return View(await _context.Carros.ToListAsync());
        }

        // GET: Carro/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        // GET: Carro/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Carro/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Marca,Modelo,AnoLancamento,AnoMontagem,Chassis")] Carro carro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(carro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(carro);
        }

        // GET: Carro/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros.FindAsync(id);
            if (carro == null)
            {
                return NotFound();
            }
            return View(carro);
        }

        // POST: Carro/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Marca,Modelo,AnoLancamento,AnoMontagem,Chassis")] Carro carro)
        {
            if (id != carro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarroExists(carro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carro);
        }

        // GET: Carro/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        // POST: Carro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carro = await _context.Carros.FindAsync(id);
            _context.Carros.Remove(carro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarroExists(int id)
        {
            return _context.Carros.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Exercicio1.Models;

namespace Exercicio1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Carro/Create.cshtml
@model Exercicio1.Models.DB.Carro

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Carro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoLancamento" class="control-label"></label>
                <input asp-for="AnoLancamento" class="form-control" />
                <span asp-validation-for="AnoLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoMontagem" class="control-label"></label>
                <input asp-for="AnoMontagem" class="form-control" />
                <span asp-validation-for="AnoMontagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Chassis" class="control-label"></label>
                <input asp-for="Chassis" class="form-control" />
                <span asp-validation-for="Chassis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Carro/Delete.cshtml
@model Exercicio1.Models.DB.Carro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Carro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoMontagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoMontagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Chassis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Chassis)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Carro/Details.cshtml
@model Exercicio1.Models.DB.Carro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Carro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoMontagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoMontagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Chassis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Chassis)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Carro/Edit.cshtml
@model Exercicio1.Models.DB.Carro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Carro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoLancamento" class="control-label"></label>
                <input asp-for="AnoLancamento" class="form-control" />
                <span asp-validation-for="AnoLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoMontagem" class="control-label"></label>
                <input asp-for="AnoMontagem" class="form-control" />
                <span asp-validation-for="AnoMontagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Chassis" class="control-label"></label>
                <input asp-for="Chassis" class="form-control" />
                <span asp-validation-for="Chassis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Carro/Index.cshtml
@model IEnumerable<Exercicio1.Models.DB.Carro>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AnoLancamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AnoMontagem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Chassis)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnoLancamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnoMontagem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Chassis)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Exercicio1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Exercicio1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carro" asp-action="Index">Gerar Carros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Exercicio1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>